SignupTitle:Vind en tur til London!
ReferralSignupTitle:Hjælp din ven og vind en tur til London!
DashboardTitle:Del med dine venner!
ConfirmSignupTitle:Du er nu tilmeldt!
TermsAndConditionsTitle:Konkurrence betingelser
InvalidActivationKeyTitle:Ugyldig aktiverings nøgle!

ChooseYourLanguage: Vælg sprog
Danish: Dansk
Swedish: Svensk
Norwegian: Norsk

FooterCopyright:copyright hvisk 2016

Competition:Konkurrence
EndsIn:Slutter om
Now:Nu

GetPrizes:Vind lækre præmier
ParticipateInTheCompetition:Tilmeld dig hvisk nyhedsbrev og deltag i konkurrencen
BonusDiscount:BONUS: Vi giver dig 50kr rabat på hvisk.com!
EmailPlaceholder:Indtast din mail...
SignupBtn:Tilmeld nu
AboutUs:Om hvisk
AboutOurNewsletter:Vores nyhedsbrev består af fashion inspiration, konkurrencer og gode tilbud.
AboutUsInformation:Enkel og edgy skandinavisk, detaljerede feminine designs, high fashion eller klassiske looks: hos hvisk ved vi, at hver kvinde har sin egen unikke og individuelle stil. Det er derfor, at vi byder på et stort udvalg af smykker, som er inspireret af trendspotting og vores Stylist fashion community, ligesom en Jewellery Republic.
FindOutMore:Opdag mere om hvisk
FindOutMoreHere:her
CompetitionRules:Konkurrence betingelser


ThanksForSigningUp:Tak for din tilmelding!
WaitForActivationMail:Du vil modtage en bekræftelsesmail inden for kort tid


Prizes:Præmier
FirstPrize:Shoppetur til London
SecondPrize:14k Infinity diamantring
ThirdPrize:500kr & 1000kr hvisk værdibeviser
DashboardInfoTitle:Inviter dine venner og vind en shoppetur til London!
DashboardInfo:Del dit unikke link via Facebook eller e-mail og optjen lodder for at vinde fantastiske præmier som hvisk smykker, Infinity 14k guld diamantring fra hvisk og vores hovedpris: en shoppetur for to til fashions storby London.
ShareThisLink:Del dette link
ShareOnFacebook:Del på facebook!
FacebookShareTitle:Værsgo! 50kr rabat på hvisk.com
FacebookShareBody:Tilmeld dig hvisks fashion nyhedsbrev og modtag 50kr rabat på hvisk.com. Happy shopping!


ParticipateInCompetitionFor:Vær med i lodtrækningen om
FirstStepPrize:500kr i hvisk smykker
SecondStepPrize:1000kr i hvisk smykker
ThridStepPrize:14k Infinity diamantring fra hvisk
FourthStepPrize:shoppetur for to til London
FriendsParticipating:Venner deltager
FriendsParticipatingCount count@Int:#{plural count "Ven" "Venner"} deltager
KeepUpdated:hold dig løbende opdateret
CheckOutHvisk:se mere på hvisk.com
BonusDiscountForYou:BONUS: Giv dine venner 50kr rabat på hvisk.com når de skriver sig ind til hvisks nyhedsbrev


AnErrorOccurred:Der skete en fejl!
NotAValidDashboardKey:Ikke en korrekt dashboard url!
FormNoContent:Indtast venligst en email!
FormNoPlus:Vi tillader desværre ikke + i mail addresser!
FormMissing:Det ser ud til at der gik noget galt. Prøv venligst at tilmelde dig igen!
FormFailure:Der var en fejl i det indsendte, brugte du en korrekt email?
FormAlreadySignedUp:Du er allerede tilmeldt!


TermsAndConditionsBy:Konkurrencen afholdes af hvisk Aps som drives af:
TermsAndConditionsByAddress:Hvisk Aps, Ny Østergade 9, 4. Sal., 1101 KØBENHAVN K, CVR-nr. 34718407
TermsAndConditionsPrizes:Hvad kan du vinde?
TermsAndConditionsPrizesInfo:Der udloddes et gavekort af 500kr til hvisk.com,  et gavekort af 1000kr til hvisk.com, 1 stk 14 k Infinity ring - værdi 9000kr (leveringstid afhænger din ringstørrelse), en tur for to til London, inkl. Flybilletter, 2 nætters overnatning i en lækker centralt hotel og 2000kr lommepenge til shopping (dato må selv bestemmes). Man kan kun vinde én premie per husstand. Du kan deltage i konkurrencen fra den 1. november til og med den  13. november 2016. Præmien kan ikke ombyttes til kontanter. Hvisk afholder præmieafgiften. Når du deler konkurrencen i dit netværk, giver du hver person der skriver sig ind til hvisks nyhedsbrev igennem din personlige link også 50kr rabat på et køb på hvisks hjemmeside der koster mere end 300kr.
TermsAndConditionsParticipation:Hvordan deltager du?
TermsAndConditionsParticipationInfo1:For at deltage i konkurrencen skal du oprette din e-mailadresse til hvisks nyhedsbrev og invitere så mange venner til nyhedsbrevet som muligt. Jo mere venner du invitere, jo større chance du har at få en lod i puljen for at vinde én af nedenstående priser:
TermsAndConditionsParticipationInfoPrize1:500 kr hvisk gavekort (ved tilmelding af 5 venner)
TermsAndConditionsParticipationInfoPrize2:1000 kr hvisk gavekort (ved tilmelding af 10 venner),
TermsAndConditionsParticipationInfoPrize3:14k infinity diamantring (ved tilmelding af 15 venner)
TermsAndConditionsParticipationInfoPrize4:Shoppetur for to til London inkl. 2 overnatninger, 2 flybilletter og lommepenge på 2000 kr (ved tilmelding af 20 venner).
TermsAndConditionsParticipationInfo2:Du deltager i lodtrækningen om én af disse premier så snart du har fået enten 5, 10, 15 eller 20 venner til at tilmelde sig hvisks nyhedsbrev. Deltagere, der forsøger at manipulere konkurrencen, udelukkes fra konkurrencen.
TermsAndConditionsWinner:Hvordan findes vinderen og hvordan får vedkommende besked?
TermsAndConditionsWinnerInfo:Vinderne findes ved lodtrækning blandt alle tilmeldinger. Vinderne får besked via e-mail og bliver trukket d. 14. november 2016. Afgørelsen af, hvem der vinder, er endelig og kan ikke ankes. Vinderen bliver offentliggjort på hvisks sociale medie sider.
TermsAndConditionsUseOfInformation:Brug af oplysninger
TermsAndConditionsUseOfInformationInfo:Hvis du tilmelder dig tilbud og information fra hvisk giver du udtrykkeligt samtykke til, at hvisk indsamler, behandler og opbevarer dine oplysninger til de formål og på de vilkår, som er beskrevet. Hvis du tilmelder dig, accepterer du ligeledes, at hvisk må sende dig tilbud og information per e-mail. Du kan til enhver tid afmelde dig igen. Hvis du har spørgsmål er du altid velkommen til at kontakte os.


Millennium:årtusinde
Millennia:årtusinder
Century:århundrede
Centuries:århundreder
Decade:årti
Decades:årtier
Year:år
Years:år
Month:månede
Months:måneder
Week:uge
Weeks:uger
Day:dag
Days:dage
Hour:time
Hours:timer
Minute:minut
Minutes:minutter
Second:sekund
Seconds:sekunder
Millisecond:millisekund
Milliseconds:millisekunder
