SignupTitle:Vind en tur til London!
ReferralSignupTitle:Hjælp din ven og vind en tur til London!
DashboardTitle:Del med dine venner!
ConfirmSignupTitle:Du er nu tilmeldt!
TermsAndConditionsTitle:Konkurransebetingelser
InvalidActivationKeyTitle:Ugyldig aktiverings nøgle!

ChooseYourLanguage: Vælg sprog
Danish: Dansk
Swedish: Svensk
Norwegian: Norsk

FooterCopyright:copyright hvisk 2016

Competition:Konkurranse
EndsIn:Slutter om
Now:Nu

GetPrizes:Vinn flotte premier
ParticipateInTheCompetition:Meld deg på hvisks nyhetsbrev og delta i konkurransen
BonusDiscount:BONUS: Vi giver dig 50kr rabat på hvisk.com!
EmailPlaceholder:Tast inn epost...
SignupBtn:Registrer deg nå
AboutUs:Om hvisk
AboutOurNewsletter:Vårt nyhetsbrev består av moteinspirasjon, konkurranser og gode tilbud.
AboutUsInformation:nkel og edgy skandinavisk, detaljert feminine designs, high fashion eller klassiske looks: hos hvisk vet vi, at hver kvinne har sin egen unike og individuelle stil. Det er derfor, vi byr på et stort utvalg av smykker, som er inspirert av trendspotting og vårt Stylist fashion community, akkurat som en Jewellery Republic.
FindOutMore:Les mer om hvisk
FindOutMoreHere:her
CompetitionRules:Konkurransebetingelser


ThanksForSigningUp:Tak for din tilmelding!
WaitForActivationMail:Du vil modtage en bekræftelsesmail inden for kort tid


Prizes:Premier
FirstPrize:Shoppingtur til London
SecondPrize:14k Infinity diamantring
ThirdPrize:500 kr & 1000 kr hvisk gavekort
DashboardInfoTitle:Inviter dine venner og vinn en shoppingtur til London!
DashboardInfo:Del din unike link via Facebook eller epost og tjen lodd for å vinne fantastiske premier som hvisk smykker, Infinity 14k gull diamantring fra hvisk og vår hovedpremie: en shoppingtur for to til motens storby London.
ShareThisLink:Del denne linken
ShareOnFacebook:Del på Facebook
FacebookShareTitle:Værsågod! 50 kr rabatt på hvisk.com
FacebookShareBody:Meld deg på hvisks fashion nyhetsbrev og motta 50 kr rabatt på hvisk.com. God shopping!


ParticipateInCompetitionFor:Vær med i lodtrækningen om
FirstStepPrize:500 kr i hvisk smykker
SecondStepPrize:1000 kr i hvisk smykker
ThridStepPrize:14k Infinity diamantring fra hvisk
FourthStepPrize:shoppingtur til London
FriendsParticipating:Venner deltager
FriendsParticipatingCount count@Int:#{plural count "Ven" "Venner"} deltager
KeepUpdated:hold dig løbende opdateret
CheckOutHvisk:se mere på hvisk.com
BonusDiscountForYou:BONUS: Giv dine venner 50kr rabat på hvisk.com når de skriver sig ind til hvisks nyhedsbrev


AnErrorOccurred:Der skete en fejl!
NotAValidDashboardKey:Ikke en korrekt dashboard url!
FormNoContent:Indtast venligst en email!
FormNoPlus:Vi tillader desværre ikke + i mail addresser!
FormMissing:Det ser ud til at der gik noget galt. Prøv venligst at tilmelde dig igen!
FormFailure:Der var en fejl i det indsendte, brugte du en korrekt email?
FormAlreadySignedUp:Du er allerede registrert!


TermsAndConditionsBy:Konkurransen avholdes av hvisk Aps som drives av:
TermsAndConditionsByAddress:Hvisk Aps, Ny Østergade 9, 4. Sal., 1101 KØBENHAVN K, CVR-nr. 34718407
TermsAndConditionsPrizes:Hva kan du vinne?
TermsAndConditionsPrizesInfo:Det loddes ut et gavekort på 500 kr hos hvisk.com,  et gavekort på 1000 kr til hvisk.com,en 14 k Infinity ring - verdi 9000 kr (leveringstid avhenger av din ringstørrelse), en tur forto til London, inkludert flybilletter, 2 netters overnatting på et flott, sentralt hotell og 2000kr i lommepenger til shopping (dato må selv bestemmes). Man kan kun vinne én premieper husstand.Du kan delta i konkurransen fra den 1 november til og med den  13. november 2016.Premien kan ikke byttes inn i konta.nter. Hvisk står for premieavgiften.Når du deler konkurransen i ditt nettverk, gir du hver person melder seg på hvisksnyhetsbrev igjennom din personlige link 50 kr rabatt på et kjøp hos hvisk som kostermer enn 300 kr.
TermsAndConditionsParticipation:Hvordan deltar du?
TermsAndConditionsParticipationInfo1:For å delta i konkurransen må du oppgi din epostadresse til hvisks nyhetsbrev oginvitere så mange venner til nyhetsbrevet som mulig. Jo flere venner du inviterer, jostørre sjanse har du for å få et lodd som vinner én av premiene nedenfor:
TermsAndConditionsParticipationInfoPrize1:500 kr hvisk gavekort (ved påmelding av 5 venner)
TermsAndConditionsParticipationInfoPrize2:1000 kr hvisk gavekort (ved påmelding av 10 venner)
TermsAndConditionsParticipationInfoPrize3:14k infinity diamantring (ved påmelding av 15 venner)
TermsAndConditionsParticipationInfoPrize4:Shoppingtur for to til London inkludert 2 overnattinger, 2 flybilletter og lommepenger på 2000 kr (ved påmelding av 20 venner).
TermsAndConditionsParticipationInfo2:Du deltar i loddtrekningen om én av disse premiene så snart du har fått 5, 10, 15 eller20 venner til å melde seg på hvisks nyhetsbrev. Deltagere, som forsøker å manipulerekonkurransen, utelukkes fra konkurransen.
TermsAndConditionsWinner:Hvordan trekkes vinneren og hvordan får vedkommende beskjed?
TermsAndConditionsWinnerInfo:Vinnerne trekkes blant alle påmeldinger ved loddtrekning. Vinnerne får beskjed via epost og blir trukket 14. november 2016. Avgjørelsen av hvem som vinner er endelig, og kan ikke ankes. Vinneren blir offentliggjort på hvisks sosiale medier.
TermsAndConditionsUseOfInformation:Bruk av opplysninger
TermsAndConditionsUseOfInformationInfo:Hvis du registrerer deg for tilbud og informasjon fra hvisk gir du samtykke til, at hvisksamler inn, behandler og oppbevarer dine opplysninger til de formål og på de vilkår,som er beskrevet.Hvis du registrerer deg, aksepterer du også at hvisk kan sende deg tilbud oginformasjon på epost. Du kan til enhver tid avregistrere deg igjen. Hvis du har spørsmåler du alltid velkommen til å kontakte oss.


Millennium:årtusinde
Millennia:årtusinder
Century:århundrede
Centuries:århundreder
Decade:årti
Decades:årtier
Year:år
Years:år
Month:månede
Months:måneder
Week:uge
Weeks:uger
Day:dag
Days:dager
Hour:time
Hours:timer
Minute:minut
Minutes:minutter
Second:sekund
Seconds:sekunder
Millisecond:millisekund
Milliseconds:millisekunder
