SignupTitle:Vinn en tur til London!
ReferralSignupTitle:Hjelp din venn, og vinn en tur til London!
DashboardTitle:Del med dine venner!
ConfirmSignupTitle:Du er nå registrert!
TermsAndConditionsTitle:Konkurransebetingelser
InvalidActivationKeyTitle:Ugyldig aktiveringsnøkkel

ChooseYourLanguage:Velg språk
Danish:Dansk
Swedish:Svensk
Norwegian:Norsk
FooterCopyright:Copyright hvisk 2016

Competition:Konkurranse
EndsIn:Slutter om
Now:Nå

GetPrizes:Vinn flotte premier
ParticipateInTheCompetition:Med deg på nyhetsbrevet og delta i konkurransen
BonusDiscount:BONUS: Vi gir deg 60kr rabatt på hvisk.com!
EmailPlaceholder:Skriv mailadressen din...
SignupBtn:Registrer deg
AboutUs:Om hvisk
AboutOurNewsletter:Vårt nyhetsbrev består av mote, inspirasjon, konkurranser og gode tilbud.
AboutUsInformation:Enkle og edgy skandinavisk, detaljerte feminiene designs, high fashion eller klassiske looks: hos hvisk vet vi at hver kvinne har sin egen unike og individuelle stil. Det er derfor vi har et stort utvalg av smykker som er inspirert av trendspotting og vårt Stylist fashion community, akkuratt som en Jewellery Republic
FindOutMore:Les mer om hvisk
FindOutMoreHere:Her
CompetitionRules:Konkurransebetingelser


ThanksForSigningUp:Takk for din registrering!
WaitForActivationMail:Du vil straks motta en bekreftelsesmail.

HowItWorksStep1:Signup og motta din unike link
HowItWorksStep2:Dele din unike link, via Facebook eller epost
HowItWorksStep3:Du motta et gavekort på 60kr hos hvisk.com
HowItWorksStep4:Tjen lodd for å stikke av med fete premier

Prizes:Premier
FirstPrize:Shoppingtur til London
SecondPrize:14k Infinity diamantring
ThirdPrize:600kr & 1200kr hvisk gavekort
DashboardInfoTitle:Inviter vennene dine og vinn en shoppingtur til London!
DashboardInfo:Del din unike link på Facebook eller via mail for å være med i trekningen om fantastiske premier som hvisk smykker, Infinity 14k gull diamantring fra hvisk og vår førstepremie: en shoppingtur for to til fashionable London.
ShareThisLink:Del denne link
ShareOnFacebook:Del på Facebook!
FacebookShareTitle:Værsågod! 60kr rabatt til hvisk.com
FacebookShareBody:Meld deg på vårt nyhetsbrev og motta 60kr rabatt på hvisk.com. Happy shopping!


ParticipateInCompetitionFor:Vær med i trekningen om
FirstStepPrize:Smykker fra hvisk til en verdi på 600kr
SecondStepPrize:Smykker fra hvisk til en verdi på 1200kr
ThridStepPrize:14k Infinity diamantring verdi 11.000kr
FourthStepPrize:Shoppingreise for to til London
FriendsParticipating:Venner deltar
FriendsParticipatingCount count@Int:#{plural count "Venn" "Venner"} deltar
KeepUpdated:Hold deg oppdatert
CheckOutHvisk:Les mer på hvisk.com
BonusDiscountForYou:BONUS: Gi vennene dine 60kr rabatt på hvisk.com når de registrerer seg hvisks nyhetsbrev


AnErrorOccurred:En feil oppsto
NotAValidDashboardKey:Ikke en korrekt dashboard url!
FormNoContent:Angi en mailadresse!
FormNoPlus:Vi tillatter dessverre ikke + i mailadresser!
FormMissing:Noe gikk galt. Prøv venligst å registrere deg i gjen.
FormFailure:Det skjedde en feil i din registrering, brukte du en korrekt mailadresse?
FormAlreadySignedUp:Du er allerede registrert!


TermsAndConditionsBy:Konkurransen holdes av hvisk Aps som drives av:
TermsAndConditionsByAddress:Hvisk Aps, Ny Østergade 9, 4. Sal., 1101 KØBENHAVN K, CVR-nr. 34718407
TermsAndConditionsPrizes:Hva kan du vinne?
TermsAndConditionsPrizesInfo:Det loddes ut et gavekort på 600kr til hvisk.com, et gavekort på 1200 kr til hvisk.com, 1 stk 14 k Infinity ring - verdi 11.000kr(leveringstid avhenger av din ringstørrelse), en tur for to til London, inkl. flybilletter, 2 netters overnatning på et flott, sentralt hotell og 2500kr i lommepenger til shopping(dato skal selv bestemmes). Man kan kun vinne én premie per husstand. Du kan delta konkurransen fra den 1. november til og med den 13. november 2016. Premien kan ikke byttes til kontanter. Hvisk betaler premieavgiften. Når du deler konkurransen i ditt nettverk, gir du hver person som registrerer seg på hvisks nyhetsbrev gjennom ditt personlige link også 60 kr rabatt på et kjøp på hvisks hjemmeside som koster med enn 350kr. Gyldig for 31. desember, 2016.
TermsAndConditionsParticipation:Hvordan deltar du?
TermsAndConditionsParticipationInfo1:For å delta i konkurransen skal du registrere deg til hvisks nyhetsbrev og invitere så mange venner som mulig til nyhetsbrevet. Jo flere venner du inviterer, jo større sjanse har du for å vinne en av premiene under:
TermsAndConditionsParticipationInfoPrize1:600 kr i gavekort til hvisk(når 5 venner har registrert seg)
TermsAndConditionsParticipationInfoPrize2:1200kr i gavekort til hvisk(når 10 venner har registrert seg)
TermsAndConditionsParticipationInfoPrize3:14k Infinity diamantring fra hvisk(når 15 venner har registrert seg)
TermsAndConditionsParticipationInfoPrize4:Shoppingtur for to til Londond inkl. 2 overnatninger og lommepenger på 2500kr(når 20 venner har registrert seg)
TermsAndConditionsParticipationInfo2:Du deltar i trekningen om én av disse premeiene så snart du har fått enten 5, 10, 15 eller 20 venner til å registrere seg på hvisks nyhetsbrev. Deltakere som forsøker å manipulere konkurransen, utelukkes fra konkurransen.
TermsAndConditionsWinner:Hvordan finnes vinneren og hvordan får vedkommende beskjed?
TermsAndConditionsWinnerInfo:Vinneren finnes ved loddtrekning blandt alle deltakere. Vinneren får beskjed via mail og blir trukket den 14. november 2016. Avgjørelsen av hvem som vinner er endelig, og kan ikke ankes. Vinneren blir offentliggjort på hvisks sosiale medier sider.
TermsAndConditionsUseOfInformation:Bruk av opplysninger
TermsAndConditionsUseOfInformationInfo:Om du registrerer deg for å motta tilbud og infomasjon fra hvisk gir du samtykke til at hvisk innsamler, behandler og oppbevarer dine opplysninger til de formål og på de vilkår som er beskrevet. Hvis du registrerer deg, aksepterer du at hvisk kan sende deg tilbud og informasjon per e-mail. Du kan alltid avmelde deg igjen. Hvis du har spørsmål, er du alltid velkommen til å kontakte oss.


Millennium:årtusen
Millennia:årtusener
Century:århundre
Centuries:århundrede
Decade:årti
Decades:årtier
Year:år
Years:år
Month:måned
Months:måneder
Week:uke
Weeks:uker
Day:dag
Days:dager
Hour:time
Hours:timer
Minute:minutt
Minutes:minutter
Second:sekund
Seconds:sekunder
Millisecond:millisekund
Milliseconds:millisekunder
