SignupTitle:Vinn en resa till London!
ReferralSignupTitle:Hjälp din vän att vinna en resa till London!
DashboardTitle:Dela med dina vänner!
ConfirmSignupTitle:Du är nu registrerad!
TermsAndConditionsTitle:Tävlingsvillkor
InvalidActivationKeyTitle:Ogiltig aktiveringsnyckel!

ChooseYourLanguage:Välj språk
Danish:Danska
Swedish:Svenska
Norwegian:Norska
FooterCopyright:Copyright hvisk 2016

Competition:Tävling
EndsIn:Slutar om
Now:Nu

GetPrizes:Vinn fina priser
ParticipateInTheCompetition:Signa upp till hvisks nyhetsbrev och delta i tävlingen
BonusDiscount:BONUS: Vi ger dig 65kr rabatt på hvisk.com!
EmailPlaceholder:Skriv in din mailadress...
SignupBtn:Registrera dig
AboutUs:Om hvisk
AboutOurNewsletter:Vår nyhetsbrev består av mode, inspiration, tävlingar och erbjudanden.
AboutUsInformation:Enkla och skandinaviska smycken, detaljerade och feminina mönster, high fashion eller klassiskt elegans - På hvisk vet vi att varje kvinna har sin egen, personliga och unika stil. Därför erbjuder vi ett stort sortiment av smycken som är inspirerade av trendspaning och vårt stylist community, precis som en Jewellery Republic.
FindOutMore:Läs mer om hvisk
FindOutMoreHere:Här
CompetitionRules:Tävlingsregler


ThanksForSigningUp:Tack för din registrering!
WaitForActivationMail:Du kommer strax att motta ett bekräftelsemail.

HowItWorksStep1:Signup och få ditt unika länk
HowItWorksStep2:Dela din unika länk via Facebook eller e-mail
HowItWorksStep3:Du får en kupong på 65kr til hvisk.com
HowItWorksStep4:Tjäna ihop till lotter för att ha chansen att vinna följande priser

Prizes:Priser
FirstPrize:Shoppingresa till London
SecondPrize:14k infinity diamantring
ThirdPrize:650kr & 1300kr i presentkort till hvisk
DashboardInfoTitle:Bjud in dina vänner och vinn en shoppingresa till London!
DashboardInfo:Dela din unika länk på Facebook eller via mail för att vara med och tävla om fantastiska priser som smycken från hvisk, diamantring Infinity 14k guld från hvisk och vårt förstapris: en shoppingresa för två till modets huvudstad London.
ShareThisLink:Dela denna länk
ShareOnFacebook:Dela på Facebook!
FacebookShareTitle:Varsågod! 65kr rabatt till hvisk.com
FacebookShareBody:Registrera dig till hvisks nyhetsbrev och få 65kr i rabatt till hvisk.com. Happy shopping!


ParticipateInCompetitionFor:Var med i utlottningen om
FirstStepPrize:Smycken från hvisk till ett värde av 650kr
SecondStepPrize:Smycken från hvisk till ett värde av 1300kr
ThridStepPrize:14k infinity diamantring värde 11.000kr
FourthStepPrize:Shoppingresa för två till London
FriendsParticipating:Deltagande vänner
FriendsParticipatingCount count@Int:#{plural count "Vän" "Vänner"} deltar
KeepUpdated:Håll dig uppdaterad
CheckOutHvisk:Läs mer på hvisk.com
BonusDiscountForYou:BONUS: Ge dina vänner 65kr i rabatt på hvisk.com när de registrerar sig till hvisks nyhetsbrev


AnErrorOccurred:Ett fel uppstod!
NotAValidDashboardKey:Dashboard URL är inte korrekt!
FormNoContent:Ange en mailadress!
FormNoPlus:Vi tillåter tyvärr inte "+" i mailadresser!
FormMissing:Något gick fel. Var vänlig testa att registrera dig igen!
FormFailure:Det uppstod ett fel i din registrering, använde du rätt mailadress?
FormAlreadySignedUp:Du är redan registrerad!


TermsAndConditionsBy:Tävlingen hållas av hvisk Aps:
TermsAndConditionsByAddress:Hvisk Aps, Ny Østergade 9, 4. Sal., 1101 KØBENHAVN K, CVR-nr. 34718407
TermsAndConditionsPrizes:Vad kan du vinna?
TermsAndConditionsPrizesInfo:Det lottas ut ett presentkort till ett värde av 650kr till hvisk.com, ett presentkort till ett värde av 1300kr till hvisk.com, en 14k infinity diamantring till ett värde av 11.000 DKK (leveranstid beror på ringstorlek), en resa till London inkl. två flygbiljetter, två nätter på ett centralt hotell och 2500kr i fickpengar till shopping (datum får du själv bestämma). Endast ett pris per hushåll. Du kan delta i tävlingen från den 1 november till och med 13 november 2016. Priset kan inte bytas till kontanter. Hvisk står för eventuella vinstskatter. När du delar tävlingen i ditt nätverk ger du varje person som signar upp till hvisks nyhetsbrev genom din personliga länk 65kr att handla för på hvisk.com, vid köp för minst 400kr. Giltigt til 31. december, 2016.
TermsAndConditionsParticipation:Hur deltar du?
TermsAndConditionsParticipationInfo1:För att delta i tävlingen måste du registrera din mailadress till hvisks nyhetsbrev och bjuda in så många vänner som möjligt till nyhetsbrevet. Ju fler vänner du bjuder in desto större chans har du att vinna en av följande priser:
TermsAndConditionsParticipationInfoPrize1:650kr i presentkort till hvisk (när 5 vänner har registrerat sig)
TermsAndConditionsParticipationInfoPrize2:1300kr i presentkort till hvisk (när 10 vänner har registrerat sig)
TermsAndConditionsParticipationInfoPrize3:14k infinity diamantring från hvisk (när 15 vänner har registrerat sig)
TermsAndConditionsParticipationInfoPrize4:Shoppingresa till London för två personer inkl. två övernattningar, två flygbiljetter och 2500 kr i fickpengar (när 20 vänner har registrerat sig).
TermsAndConditionsParticipationInfo2:Du deltar i dragningen om en av dessa priser när du fått 5, 10, 15 eller 20 vänner att registrera sig till hvisks nyhetsbrev. Deltagare som försöker manipulera tävlingen kommer diskvalificeras.
TermsAndConditionsWinner:Hur utses vinnaren och hur kontaktas denna?
TermsAndConditionsWinnerInfo:Vinnaren utses genom lottdragning av alla deltagare. Vinnaren dras den 14 november 2016 och meddelas via mail. Beslutet av vem som vinner är slutgiltigt och kan inte överklagas. Vinnaren meddelas också på hvisks sociala medier.
TermsAndConditionsUseOfInformation:Användning av uppgifter
TermsAndConditionsUseOfInformationInfo:Om du registrerar dig för att motta erbjudande och information från hvisk samtycker du till att hvisk samlar in, behandlar och lagrar dina uppgifter för de ändamål och på de villkor som beskrivs. Om du registrerar dig accepterar du att hvisk skickar erbjudande och information via e-post. Du kan alltid avsluta din prenumeration. Om du har frågor är du välkommen att kontakta oss.


Millennium:årtusende
Millennia:årtusenden
Century:århundrade
Centuries:århundraden
Decade:årtionde
Decades:årtionden
Year:år
Years:år
Month:månad
Months:månader
Week:vecka
Weeks:veckor
Day:dag
Days:dagar
Hour:timma
Hours:timmar
Minute:minut
Minutes:minuter
Second:sekund
Seconds:sekunder
Millisecond:millisekund
Milliseconds:millisekunder
