SignupTitle:Vind en tur til London!
ReferralSignupTitle:Hjælp din ven og vind en tur til London!
DashboardTitle:Del med dine venner!
ConfirmSignupTitle:Du er nu tilmeldt!
TermsAndConditionsTitle:Tävlingsvillkor
InvalidActivationKeyTitle:Ugyldig aktiverings nøgle!

ChooseYourLanguage: Vælg sprog
Danish: Dansk
Swedish: Svensk
Norwegian: Norsk

FooterCopyright:copyright hvisk 2016

Competition:Tävlingen
EndsIn:Slutar om
Now:Nu

GetPrizes:Vinn spännande priser
ParticipateInTheCompetition:Anmäl dig till hvisks nyhetsbrev och delta i tävlingen
BonusDiscount:BONUS: Vi giver dig 50kr rabat på hvisk.com!
EmailPlaceholder:Ange e-post...
SignupBtn:Registrera dig nu
AboutUs:Om hvisk
AboutOurNewsletter:Vårt nyhetsbrev består av modeinspiration, tävlingar och specialerbjudanden.
AboutUsInformation:Enkla och edgy skandinaviska smycken i detaljerad feminin design, high fashion eller klassiska looks: hos hvisk vet vi att varje kvinna har sin egen unika och individuella stil. Det är därför vi erbjuder ett stort urval av smycken, som är inspirerade av trendspaning och vårt Stylist fashion community, precis som Jewellery Republic.
FindOutMore:Upptäck mer om hvisk här
FindOutMoreHere:här
CompetitionRules:Tävlingsvillkor


ThanksForSigningUp:Tak for din tilmelding!
WaitForActivationMail:Du vil modtage en bekræftelsesmail inden for kort tid


Prizes:Priser
FirstPrize:Shoppingresa till London
SecondPrize:14k Infinity diamantring
ThirdPrize:500 kr & 1000 kr presentkort hos hvisk
DashboardInfoTitle:Bjud in dina vänner och vinn en shoppingresa till London!
DashboardInfo:Dela din unika länk via Facebook eller e-post och få lotter som gör att du kan vinna fantastiska priser så som: hvisk-smycken, Infinity diamantring i 14k guld från hvisk och vårt huvudpris: En shoppingresa för två till modemetropolen London.
ShareThisLink:Dela denna länk
ShareOnFacebook:Dela på Facebook
FacebookShareTitle:Varsågod! 50 kr rabatt på hvisk.com
FacebookShareBody:Anmäl dig till hvisks fashion nyhetsbrev och få 50 kr rabatt på hvisk.com. Happy shopping!


ParticipateInCompetitionFor:Vær med i lodtrækningen om
FirstStepPrize:hvisk-smycken för 500 kr
SecondStepPrize:hvisk-smycken för 1000 kr
ThridStepPrize:14k Infinity diamantring från hvisk
FourthStepPrize:shoppingresa till London
FriendsParticipating:Venner deltager
FriendsParticipatingCount count@Int:#{plural count "Ven" "Venner"} deltager
KeepUpdated:hold dig løbende opdateret
CheckOutHvisk:se mere på hvisk.com
BonusDiscountForYou:BONUS: Giv dine venner 50kr rabat på hvisk.com når de skriver sig ind til hvisks nyhedsbrev


AnErrorOccurred:Der skete en fejl!
NotAValidDashboardKey:Ikke en korrekt dashboard url!
FormNoContent:Indtast venligst en email!
FormNoPlus:Vi tillader desværre ikke + i mail addresser!
FormMissing:Det ser ud til at der gik noget galt. Prøv venligst at tilmelde dig igen!
FormFailure:Der var en fejl i det indsendte, brugte du en korrekt email?
FormAlreadySignedUp:Du har redan registrerat dig!


TermsAndConditionsBy:Tävlingen hålls av hvisk Aps som drivs av:
TermsAndConditionsByAddress:Hvisk Aps, Ny Østergade 9, 4. Sal., 1101 KØBENHAVN K, CVR-nr. 34718407
TermsAndConditionsPrizes:Vad kan du vinna?
TermsAndConditionsPrizesInfo:Vi lottar ut ett presentkort på 500 kr hos hvisk.com, ett presentkort på 1000 kr hos hvisk.com, enInfinity-ring i 14 karats guld - värde 9000 kr (leveranstid beror på din ringstorlek), en resa för tvåtill London, inkl. flyg, två nätter på ett trevligt centralt hotell och 2000 kr fickpengar för shopping(datum bestämmer du själv). Du kan bara vinna ett pris per hushåll. Du kan delta i tävlingen från den 1 november till och med den 13 november 2016. Priset kan inte bytas mot kontanter. Hvisk står inte för eventuell vinstskatt. Om du delar tävlingen med ditt nätverk, får varje person som anmäler sig till hvisks nyhetsbrevvia din personliga länk också 50 kr rabatt på valfritt köp över 300 kr på hvisks webbplats.
TermsAndConditionsParticipation:Hur deltar du?
TermsAndConditionsParticipationInfo1:För att delta i tävlingen måste du anmäla din e-postadress till hvisks nyhetsbrev och bjuda in såmånga vänner som möjligt att prenumerera på nyhetsbrevet. Ju fler vänner du bjuder in, destostörre chans har du att få en del av potten och vinna ett av följande priser:
TermsAndConditionsParticipationInfoPrize1:500 kr presentkort hos hvisk (vid registrering av 5 vänner)
TermsAndConditionsParticipationInfoPrize2:1000 kr presentkort hos hvisk (vid registrering av 10 vänner)
TermsAndConditionsParticipationInfoPrize3:14k infinity diamantring (vid registrering av 15 vänner)
TermsAndConditionsParticipationInfoPrize4:Shoppingresa för två till London inkl. 2 övernattningar, 2 flygbiljetter och fickpengar på 2.000 kr (vid registrering av 20 vänner).
TermsAndConditionsParticipationInfo2:Du deltar i utlottningen av ett av dessa priser så snart du samlat på dig antingen 5, 10, 15 eller 20 vänner att registrera sig till hvisks nyhetsbrev. Deltagare som försöker manipulera tävlingenkommer att uteslutas från tävlingen.
TermsAndConditionsWinner:Hur utses vinnarna och hur får de besked om att de vunnit?
TermsAndConditionsWinnerInfo:Vinnarna kommer att dras genom lottning av alla kvalificerade deltagare. Vinnarna meddelas viae-post och kommer att dras den 14 november 2016. Beslutet om vem som vinner är slutgiltigt och kan inte överklagas. Vinnaren kommer atttillkännages på hvisks sociala medier.
TermsAndConditionsUseOfInformation:Användandet av persondata
TermsAndConditionsUseOfInformationInfo:Om du registrerar dig för erbjudanden och information från hvisk, ger du samtidigt samtycke tillatt låta hvisk samlar in, bearbeta och lagra din information för de ändamål och på de villkor sombeskrivs.Om du registrerar dig accepterar du likväl att hvisk kan komma att skicka dig erbjudanden ochinformation via e-post. Du kan alltid avsluta din prenumeration. Om du har några frågor är duvälkommen att kontakta oss.


Millennium:årtusinde
Millennia:årtusinder
Century:århundrede
Centuries:århundreder
Decade:årti
Decades:årtier
Year:år
Years:år
Month:månede
Months:måneder
Week:uge
Weeks:uger
Day:dag
Days:dagar
Hour:time
Hours:timmar
Minute:minut
Minutes:minuter
Second:sekund
Seconds:sekunder
Millisecond:millisekund
Milliseconds:millisekunder
